### ISSUE TITLE
Review of Stable Branch

### ISSUE THREAD

**Issue by shinn16** [MUGeeksandGadgets/MUGeeksandGadgets.github.io#9]
After updating the dev branch and then merging to stable which them merged to master, I think we need to re-evaluate the need for the stable branch. Master pretty much is stable.

**Comment by bmduke1997** [comment]
I agree completely. Would you like me to delete stable?

**Comment by shinn16** [comment]
Go for it!


Sent via the Samsung Galaxy Note® 3, an AT&T 4G LTE smartphone

-------- Original message --------
